about:
  image: assets/img/portrait.jpg
  text: >-
    <p>Hello! I’m Michael Bodell. I am a project manager with over 23 years of
    proffesional leadership and managment experience. </p>
  list:
    - label: Name
      value: Michael Bodell
    - label: Address
      value: 'York, Pa'
    - label: Work Status
      value: Available
    - label: Country
      value: USA
    - label: E-mail
      value: mikebodell@gmail.com
  download:
    text: Download CV
    link: >-
      https://drive.google.com/file/d/1l6fSBIxmrW9dgfAw5zszPypXBt6Kfr9a/view?usp=sharing
services:
  title: Skills
  items:
    - icon: fas fa-users
      name: Project Management
      text: Team builder
    - icon: fas fa-music
      name: Agilist
      text: like a symphony
    - icon: fas fa-ad
      name: Advetising
      text: >-
        Advertising services include television, radio, print, mail, and web
        apps.
    - icon: fas fa-gamepad
      name: Game Development
      text: 'Developing memorable and unique mobile android, ios and video games.'
    - icon: fas fa-camera
      name: Photography
      text: >-
        Our in-house photography services team made up of professional
        photographers.
    - icon: fas fa-mobile-alt
      name: Android Application
      text: >-
        Games, playing music, handle network transactions, interacting content
        etc.
resume:
  experience:
    title: Experience
    items:
      - year: 2017 - Present
        name: Senior Project Manager
        text: ''
      - year: 2005 - 2017
        name: Information Technology System Administrator/Manager
        text: ''
  education:
    title: Education
    items:
      - year: Summer 2022
        name: Penn State University
        text: Matriculated in Business Administration Program
      - year: 2000-2002
        name: University of the Arts
        text: Photography Major
skills:
  columns:
    - type: list
      title: Technical Knowledge
      items:
        - label: Website/Infastructure hosting
          value: ''
        - label: Server virtualization technologies
          value: ''
        - label: OCR Processing
          value: ''
        - label: ERP Solutions
          value: ''
        - label: Windows Server/Client Infastructure
          value: ''
        - label: ETL/ELT data transformation
          value: ''
        - label: Point of Sale / OPOS
          value: ''
        - label: IT Hardware Infastructure
          value: ''
    - type: default
      title: Design Skills
      items:
        - label: Web Design
          value: 70
        - label: Illustrations
          value: 90
        - label: Photoshop
          value: 75
        - label: Graphic Design
          value: 80
    - type: dotted
      title: Project Management Styles
      items:
        - label: Agile
          value: 80
        - label: Six Sigma
          value: 65
        - label: Waterfall
          value: 90
    - type: circles
      title: Coding Skills
      items:
        - label: WordPress
          value: 85
        - label: PHP / MYSQL
          value: 75
        - label: React/ JavaScript
          value: 70
        - label: HTML / CSS
          value: 70
facts:
  title: Interests
  items:
    - icon: fas fa-hockey-puck
      name: Hockey
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
    - icon: fas fa-campground
      name: Camping
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
    - icon: fas fa-chess-knight
      name: Chess
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
    - icon: fas fa-headphones
      name: Music
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
team:
  title: Our Team
  items:
    - image: assets/img/team/team1.jpg
      name: Michael Bodell
      role: Project Manager
      social:
        - url: 'https://github.com/guitar82'
          icon: fab fa-github
        - url: 'https://www.linkedin.com/in/mikebodell'
          icon: fab fa-linkedin
testimonials:
  title: Testimonials
  items:
    - image: assets/img/testimonials/rev1.jpg
      name: null
      role: Art Director
      text: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
        dolor sit amet, consectetur adipiscing elit.
    - image: assets/img/testimonials/rev1.jpg
      name: Helen Floyd
      role: Art Director
      text: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
        dolor sit amet, consectetur adipiscing elit.
clients:
  title: Clients
  items:
    - url: 'https://www.google.com'
      image: assets/img/clients/client1.png
    - url: 'https://www.google.com'
      image: assets/img/clients/client2.png
    - url: 'https://www.google.com'
      image: assets/img/clients/client3.png
    - url: 'https://www.google.com'
      image: assets/img/clients/client4.png
text:
  title: Custom Text
  text: <p> Text </p> <p> Text </p>
contacts_info:
  title: Contacts Info
  list:
    - label: Phone
      icon: fas fa-phone
      value: + (717) 341 52 32
    - label: Email
      icon: fas fa-envelope
      value: '&#109;&#105;&#107;&#101;&#098;&#111;&#100;&#101;&#108;&#108;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;'
    - label: Address
      icon: fas fa-map-marker-alt
      value: 'York, Pennsylvania'
    - label: Open to work
      icon: fas fa-user-tie
      value: I am open to new opportunities.
contacts_form:
  title: Contact Form