# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  logo_text: "Michael <strong>Bodell</strong>"
  logo_hover_text: "Download <strong>CV</strong>"
  quick_colors: "blue" # select quick color schemes: "beige", "blue", "brown", "green_light", "green", "orange", "purple", "red", "yellow_light", "yellow". If empty colors taken from _sass/ryancv/settings.scss
  logo_url: "https://drive.google.com/file/d/1mE4R8bQOAJ1B7uvdr6WwJ2jaybJY1u0C/view?usp=sharing"

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "Video"
      slug: "f-video"

    - name: "Music"
      slug: "f-music"

    - name: "Links"
      slug: "f-link"

    - name: "Image"
      slug: "f-image"

    - name: "Gallery"
      slug: "f-gallery"

    - name: "Content"
      slug: "f-content"
